#!/usr/bin/env tsx
/**
 * Noctis Contract Deployment & Configuration Script
 *
 * Reads secrets from environment variables (never hardcoded), deploys all
 * five Soroban contracts to testnet, runs their post-deploy configuration,
 * and writes the new addresses back into .env.testnet.
 *
 * Usage:
 *   TESTNET_RPC_URL=https://soroban-testnet.stellar.org \
 *   PASSKEYGATE_DEPLOYER_SECRET=<secret> \
 *   LOCAL_DEPLOYER_SECRET=<secret> \
 *   npx tsx scripts/deploy-and-configure.ts
 */

import { execSync } from "child_process";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";

// ─── Types ────────────────────────────────────────────────────────────────

interface ContractDef {
  name: string;
  wasm: string;
  deployArgs?: string[];
  configureArgs?: string[];
}

interface DeployResult {
  name: string;
  address: string;
  success: boolean;
  error?: string;
}

// ─── Configuration ────────────────────────────────────────────────────────

const ENV_FILE = resolve(import.meta.dirname, "..", ".env.testnet");

const CONTRACTS: ContractDef[] = [
  {
    name: "wallet_factory",
    wasm: "target/wasm32v1-none/release/wallet_factory.wasm",
    deployArgs: ["--admin", "$(cat .admin_address)"],
  },
  {
    name: "policy_signer",
    wasm: "target/wasm32v1-none/release/policy_signer.wasm",
    deployArgs: ["--admin", "$(cat .admin_address)"],
  },
  {
    name: "payroll_dispatcher",
    wasm: "target/wasm32v1-none/release/payroll_dispatcher.wasm",
    deployArgs: ["--admin", "$(cat .admin_address)"],
    configureArgs: [
      "--token", "$CONTRACT_TOKEN_ADDRESS",
      "--trusted_setup_hash", "0100000000000000000000000000000000000000000000000000000000000001",
    ],
  },
  {
    name: "streaming_vault",
    wasm: "target/wasm32v1-none/release/streaming_vault.wasm",
    deployArgs: ["--admin", "$(cat .admin_address)"],
  },
  {
    name: "yield_router",
    wasm: "target/wasm32v1-none/release/yield_router.wasm",
    deployArgs: ["--admin", "$(cat .admin_address)"],
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────

function getEnvOrExit(key: string): string {
  const val = process.env[key];
  if (!val) {
    console.error(`Missing required env var: ${key}`);
    process.exit(1);
  }
  return val;
}

function run(cmd: string, label: string): string {
  try {
    const output = execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] });
    console.log(`  ✅ ${label}`);
    return output.trim();
  } catch (err: any) {
    const msg = err.stderr?.trim() || err.message || "Unknown error";
    throw new Error(`Command failed (${label}): ${msg}`);
  }
}

function parseDeployAddress(raw: string): string {
  // stellar contract deploy outputs the contract ID on the last line
  const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
  const last = lines[lines.length - 1];
  // Contract IDs on Stellar testnet start with 'C'
  if (last && last.startsWith("C")) return last;
  // Try to find any line starting with C
  for (const line of lines) {
    if (line.startsWith("C")) return line;
  }
  throw new Error(`Could not parse contract address from output:\n${raw}`);
}

function loadEnvFile(): Record<string, string> {
  if (!existsSync(ENV_FILE)) {
    console.warn("  ⚠️  .env.testnet not found — starting fresh");
    return {};
  }
  const raw = readFileSync(ENV_FILE, "utf8");
  const env: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (key) env[key] = val;
  }
  return env;
}

function saveEnvFile(env: Record<string, string>): void {
  const keys = Object.keys(env).sort();
  const lines: string[] = [
    "# ============================================================================",
    "# NOCTIS TESTNET ENVIRONMENT CONFIGURATION",
    "# File: .env.testnet",
    "# NOTE: This file was auto-generated by deploy-and-configure.ts",
    "# ============================================================================",
    "",
  ];
  for (const key of keys) {
    lines.push(`${key}=${env[key]}`);
  }
  lines.push("");
  writeFileSync(ENV_FILE, lines.join("\n"), "utf8");
  console.log(`  📝 Updated ${ENV_FILE}`);
}

// ─── Main ─────────────────────────────────────────────────────────────────

async function main() {
  console.log("=".repeat(60));
  console.log("  NOCTIS CONTRACT DEPLOYMENT & CONFIGURATION");
  console.log("=".repeat(60));

  // Validate environment
  const passkeygateSecret = getEnvOrExit("PASSKEYGATE_DEPLOYER_SECRET");
  const localDeployerSecret = getEnvOrExit("LOCAL_DEPLOYER_SECRET");
  const rpcUrl = getEnvOrExit("TESTNET_RPC_URL");

  console.log(`  Network:     Stellar Testnet`);
  console.log(`  RPC:         ${rpcUrl}`);
  console.log(`  Deployer:    passkeygate-deployer (${passkeygateSecret.slice(0, 4)}...)`);
  console.log(`  Token Admin: local-deployer (${localDeployerSecret.slice(0, 4)}...)`);
  console.log("");

  // Step 1: Ensure Stellar CLI keys are installed
  console.log("═══ Step 1: Ensure deployer identities ═══\n");
  try {
    run("stellar keys list", "Check existing keys");
  } catch {
    run(
      `echo "${passkeygateSecret}" | stellar keys add passkeygate-deployer --secret-stdin`,
      "Add passkeygate-deployer",
    );
    run(
      `echo "${localDeployerSecret}" | stellar keys add local-deployer --secret-stdin`,
      "Add local-deployer",
    );
  }

  // Step 2: Ensure testnet network is configured
  console.log("\n═══ Step 2: Configure Stellar network ═══\n");
  try {
    run("stellar network ls", "Check networks");
  } catch {
    // network may not be configurable via this command; handled separately
  }

  // Step 3: Deploy all contracts
  console.log("\n═══ Step 3: Deploy contracts ═══\n");
  const results: DeployResult[] = [];
  let allSuccess = true;

  for (const contract of CONTRACTS) {
    try {
      console.log(`  Deploying ${contract.name}...`);
      const deployCmd = [
        "stellar contract deploy",
        `--wasm ${contract.wasm}`,
        "--source-account passkeygate-deployer",
        "--network testnet",
        contract.deployArgs?.join(" ") ?? "",
      ]
        .filter(Boolean)
        .join(" ");

      const rawOutput = run(deployCmd, `${contract.name} deployed`);
      const address = parseDeployAddress(rawOutput);
      console.log(`    Address: ${address}`);
      results.push({ name: contract.name, address, success: true });
    } catch (err: any) {
      console.error(`  ❌ ${contract.name} deployment FAILED: ${err.message}`);
      results.push({ name: contract.name, address: "", success: false, error: err.message });
      allSuccess = false;
    }
  }

  // Step 4: Configure contracts that need post-deploy setup
  console.log("\n═══ Step 4: Configure contracts ═══\n");
  for (const contract of CONTRACTS) {
    if (!contract.configureArgs || contract.configureArgs.length === 0) continue;

    const result = results.find((r) => r.name === contract.name);
    if (!result || !result.success) {
      console.warn(`  ⚠️  Skipping configure for ${contract.name} — deployment failed`);
      continue;
    }

    try {
      const configureCmd = [
        "stellar contract invoke",
        `--id ${result.address}`,
        "--source-account passkeygate-deployer",
        "--network testnet",
        "-- configure",
        ...contract.configureArgs,
      ]
        .filter(Boolean)
        .join(" ");

      run(configureCmd, `${contract.name} configured`);
    } catch (err: any) {
      console.error(`  ❌ ${contract.name} configuration FAILED: ${err.message}`);
      allSuccess = false;
    }
  }

  // Step 5: Update .env.testnet with new addresses
  console.log("\n═══ Step 5: Update .env.testnet ═══\n");
  const env = loadEnvFile();
  for (const result of results) {
    const key = `CONTRACT_${result.name.toUpperCase()}_ADDRESS`;
    if (result.success) {
      env[key] = result.address;
    }
  }
  saveEnvFile(env);

  // Step 6: Print summary
  console.log("\n" + "=".repeat(60));
  console.log("  DEPLOYMENT SUMMARY");
  console.log("=".repeat(60));
  for (const r of results) {
    const icon = r.success ? "✅" : "❌";
    console.log(`  ${icon} ${r.name}: ${r.success ? r.address : r.error}`);
  }
  console.log("=".repeat(60));

  if (!allSuccess) {
    console.error("\n⚠️  One or more deployments failed — see above for details");
    process.exit(1);
  }

  console.log("\n🎉 All contracts deployed and configured successfully!");
}

main().catch((err) => {
  console.error("\n❌ Fatal error:", err.message);
  process.exit(1);
});
